### ISSUE TITLE
retail leap year for 445 calendar adds a week to the eleventh month

### ISSUE THREAD

**Issue by mikfreedman** [holonk/retail-calendar#21]
I have a need to provide a different leap year strategy to retail-calendar aside from `restated` or `drop first week`.

Naturally, it's hard to find detailed examples of how this works but I managed to find this specification that details what I'm talking about:

>     Below is an example of the coded $DWMY445 that uses a 4-
>     4-5 accounting calendar.  The first year starts on
>     02JAN84 and ends on 30DEC84.  Each week begins on Monday.
>     The accounting year that has 53 weeks is 1989.  The 11th
>     month has the extra week in the 53 week year.  The two
>     years in the sample that begin in the same year as the
>     accounting year have the starting dates of 02JAN84 and
>     01JAN90

_from:_ [4.7.2.3 Calendar Modifications for 445/454/544 Calendars
](https://ftpdocs.broadcom.com/cadocs/0/CA%20MICS%20Resource%20Management%2012%207%2000-ENU/Bookshelf_Files/HTML/SystemModificationGuide/M4723.html)

**Comment by cihancimen** [comment]
Fixed in [1.6.0](https://github.com/holonk/retail-calendar/releases/tag/v1.6.0)

**Comment by cihancimen** [comment]
1.6.0 is published as [npm package](https://www.npmjs.com/package/retail-calendar).
