### ISSUE TITLE
addLeapWeekToMonth ignored when 0

### ISSUE THREAD

**Issue by toinfinity86** [holonk/retail-calendar#54]
Hi,

First of all, thank you for your work.

We noticed that addLeapWeekToMonth: 0 is ignored.
This is due to a mistake in retail_calendar.ts line 241.
You should replace 
` this.options.addLeapWeekToMonth &&`

with
` this.options.addLeapWeekToMonth !== undefined &&`

Thank you

**Comment by cihancimen** [comment]
This is fixed in version 4.1.2
